# Generated by Django 5.2.4 on 2025-07-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='descuento_cliente',
            field=models.FloatField(default=0.0, verbose_name='Descuento Cliente (%)'),
        ),
    ]
