# Generated by Django 5.2.4 on 2025-07-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_descuento_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_method',
            field=models.CharField(choices=[('EM', 'Email'), ('WA', 'WhatsApp')], default='EM', max_length=2, verbose_name='Método de autenticación'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de WhatsApp'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WhatsAppVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['number'], name='users_whats_number_dd44ec_idx')],
            },
        ),
    ]
