# Generated by Django 5.2.4 on 2025-07-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_auth_method_customuser_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappverification',
            name='resend_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='whatsappverification',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
