# Generated by Django 5.2.4 on 2025-07-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                # ... solo campos de EmailConfig ...
            ],
        ),
    ]
