# Generated by Django 5.2.4 on 2025-07-26 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='protected_users',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que no pueden ser eliminados', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios protegidos'),
        ),
    ]
