# Generated by Django 5.2.4 on 2025-07-26 21:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Sucursal')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Marca')),
                ('logo_url', models.URLField(blank=True, max_length=500, verbose_name='Logo URL')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], default='CREATE', max_length=6, verbose_name='Acción')),
                ('field', models.CharField(db_index=True, max_length=50, verbose_name='Campo Modificado')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Nuevo Valor')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha/Hora')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos Adicionales')),
            ],
            options={
                'verbose_name': 'Registro de Cambio',
                'verbose_name_plural': 'Historial de Cambios',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Tipo de cambio')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, max_length=50)),
                ('update_type', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo de cambio',
                'verbose_name_plural': 'Tipos de cambio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Característica')),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Normal')),
                ('special', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Especial')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio con Descuento')),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Lista')),
                ('margin', models.FloatField(default=20.0, verbose_name='Margen (%)')),
                ('margen_prod', models.FloatField(default=0.2, verbose_name='Margen Producto (%)')),
                ('descuento_prod', models.FloatField(default=0.0, verbose_name='Descuento Producto (%)')),
                ('price_edited', models.BooleanField(default=False, verbose_name='Precio Editado Manualmente')),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syscom_id', models.CharField(max_length=12, unique=True, verbose_name='ID Syscom')),
                ('model', models.CharField(max_length=255, verbose_name='Modelo')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('warranty', models.CharField(blank=True, max_length=50, verbose_name='Garantía')),
                ('sat_key', models.CharField(blank=True, max_length=20, verbose_name='Clave SAT')),
                ('private_link', models.URLField(blank=True, max_length=500, verbose_name='Link Privado')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('main_image', models.URLField(blank=True, max_length=500, verbose_name='Imagen Principal')),
                ('brand_logo', models.URLField(blank=True, max_length=500, verbose_name='Logo Marca')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronización')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible al Público')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Relación Producto-Categoría',
                'verbose_name_plural': 'Relaciones Producto-Categoría',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL de Imagen')),
                ('type', models.CharField(choices=[('adicional', 'Adicional'), ('thumbnail', 'Miniatura'), ('galeria', 'Galería')], default='adicional', max_length=10, verbose_name='Tipo de Imagen')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Producto',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Recurso')),
                ('url', models.URLField(max_length=500, verbose_name='URL del Recurso')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.CreateModel(
            name='SyscomCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=120)),
                ('client_secret', models.CharField(max_length=256)),
                ('token', models.CharField(blank=True, max_length=1224)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credencial Syscom',
                'verbose_name_plural': 'Credenciales Syscom',
            },
        ),
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.branch', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Existencia en Sucursal',
                'verbose_name_plural': 'Existencias en Sucursales',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Categoría')),
                ('level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nivel')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='Categoría padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['level', 'name'],
            },
        ),
    ]
