# Generated by Django 5.2.4 on 2025-07-26 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_made', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='ProductIcon',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='icons', serialize=False, to='products.product', verbose_name='Producto')),
                ('top_left', models.URLField(blank=True, max_length=500, verbose_name='Icono Superior Izquierdo')),
                ('top_right', models.URLField(blank=True, max_length=500, verbose_name='Icono Superior Derecho')),
            ],
            options={
                'verbose_name': 'Icono de Producto',
                'verbose_name_plural': 'Iconos de Producto',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='feature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='products.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='branchstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='products.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(through='products.ProductCategory', to='products.category', verbose_name='Categorías'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='resource',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='products.product', verbose_name='Producto'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['product', 'field'], name='products_ch_product_b86ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['timestamp', 'user'], name='products_ch_timesta_72aa23_idx'),
        ),
        migrations.AddIndex(
            model_name='branchstock',
            index=models.Index(fields=['branch', 'quantity'], name='products_br_branch__89aae0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branchstock',
            unique_together={('product', 'branch')},
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('product', 'category')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['syscom_id'], name='products_pr_syscom__86042e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['model'], name='products_pr_model_268e30_idx'),
        ),
    ]
