# Generated by Django 5.2.4 on 2025-07-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='descuento_prod',
            field=models.FloatField(default=0.0, verbose_name='Descuento Producto (%)'),
        ),
        migrations.AddField(
            model_name='price',
            name='margen_prod',
            field=models.FloatField(default=0.2, verbose_name='Margen Producto (%)'),
        ),
    ]
