# Generated by Django 5.2.3 on 2025-06-19 08:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Sucursal')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_type', models.CharField(choices=[('n', 'Normal'), ('a', 'Asterisco A'), ('b', 'Asterisco B')], default='n', max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Existencia por sucursal',
                'verbose_name_plural': 'Existencias por sucursal',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Marca')),
                ('logo_url', models.URLField(blank=True, max_length=500, verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Categoría')),
                ('level', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=500, null=True)),
                ('new_value', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Historial de cambio',
                'verbose_name_plural': 'Historial de cambios',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Tipo de cambio')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, max_length=50)),
                ('update_type', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo de cambio',
                'verbose_name_plural': 'Tipos de cambio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('local', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('portada', 'portada'), ('thumbnail', 'thumbnail'), ('adicional', 'adicional'), ('icono', 'icono'), ('marca_logo', 'marca_logo')], default='adicional', max_length=15)),
                ('is_main', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SyscomCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=120)),
                ('client_secret', models.CharField(max_length=256)),
                ('token', models.CharField(blank=True, max_length=1224)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credencial Syscom',
                'verbose_name_plural': 'Credenciales Syscom',
            },
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_sku_ca0cdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_name_9ff0a3_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0.0, verbose_name='Descuento %'),
        ),
        migrations.AddField(
            model_name='product',
            name='list_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Precio lista'),
        ),
        migrations.AddField(
            model_name='product',
            name='margin',
            field=models.FloatField(default=20.0, verbose_name='Margen %'),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_edited',
            field=models.BooleanField(default=False, verbose_name='Precio editado'),
        ),
        migrations.AddField(
            model_name='product',
            name='private_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link privado'),
        ),
        migrations.AddField(
            model_name='product',
            name='public_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Precio público'),
        ),
        migrations.AddField(
            model_name='product',
            name='sat_key',
            field=models.CharField(blank=True, max_length=20, verbose_name='Clave SAT'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=700, verbose_name='Descripción corta'),
        ),
        migrations.AddField(
            model_name='product',
            name='special_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Precio especial'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='product',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Visible al público'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='branchstock',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.branch'),
        ),
        migrations.AddField(
            model_name='branchstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='Categoría padre'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='products.product'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', through='products.ProductCategory', to='products.category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['model'], name='products_pr_model_268e30_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='products_pr_title_7d8124_idx'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='branchstock',
            unique_together={('product', 'branch')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='products_ca_name_693421_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('product', 'category')},
        ),
    ]
