# Generated by Django 5.2.3 on 2025-06-24 21:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_branch_branchstock_brand_category_changelog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Característica')),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='prices', serialize=False, to='products.product', verbose_name='Producto')),
                ('normal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Normal')),
                ('special', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Especial')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio con Descuento')),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Lista')),
                ('margin', models.FloatField(default=20.0, verbose_name='Margen (%)')),
                ('price_edited', models.BooleanField(default=False, verbose_name='Precio Editado Manualmente')),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
            },
        ),
        migrations.CreateModel(
            name='ProductIcon',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='icons', serialize=False, to='products.product', verbose_name='Producto')),
                ('top_left', models.URLField(blank=True, max_length=500, verbose_name='Icono Superior Izquierdo')),
                ('top_right', models.URLField(blank=True, max_length=500, verbose_name='Icono Superior Derecho')),
            ],
            options={
                'verbose_name': 'Icono de Producto',
                'verbose_name_plural': 'Iconos de Producto',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Recurso')),
                ('url', models.URLField(max_length=500, verbose_name='URL del Recurso')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.AlterModelOptions(
            name='branchstock',
            options={'verbose_name': 'Existencia en Sucursal', 'verbose_name_plural': 'Existencias en Sucursales'},
        ),
        migrations.AlterModelOptions(
            name='changelog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Registro de Cambio', 'verbose_name_plural': 'Historial de Cambios'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Relación Producto-Categoría', 'verbose_name_plural': 'Relaciones Producto-Categoría'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order'], 'verbose_name': 'Imagen de Producto', 'verbose_name_plural': 'Imágenes de Producto'},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='products_ca_name_693421_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_title_7d8124_idx',
        ),
        migrations.RemoveField(
            model_name='branchstock',
            name='stock_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='list_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_edited',
        ),
        migrations.RemoveField(
            model_name='product',
            name='public_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_price',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='local',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='changelog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], default='CREATE', max_length=6, verbose_name='Acción'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadatos Adicionales'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_logo',
            field=models.URLField(blank=True, max_length=500, verbose_name='Logo Marca'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.URLField(blank=True, max_length=500, verbose_name='Imagen Principal'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=50, verbose_name='Garantía'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='branchstock',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.branch', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='branchstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='products.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='branchstock',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='branchstock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Logo URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='field',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Campo Modificado'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='new_value',
            field=models.TextField(blank=True, null=True, verbose_name='Nuevo Valor'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='old_value',
            field=models.TextField(blank=True, null=True, verbose_name='Valor Anterior'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='products.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha/Hora'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_made', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(through='products.ProductCategory', to='products.category', verbose_name='Categorías'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronización'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='private_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link Privado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='syscom_id',
            field=models.CharField(max_length=12, unique=True, verbose_name='ID Syscom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='product',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible al Público'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='type',
            field=models.CharField(choices=[('adicional', 'Adicional'), ('thumbnail', 'Miniatura'), ('galeria', 'Galería')], default='adicional', max_length=10, verbose_name='Tipo de Imagen'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.URLField(max_length=500, verbose_name='URL de Imagen'),
        ),
        migrations.AddIndex(
            model_name='branchstock',
            index=models.Index(fields=['branch', 'quantity'], name='products_br_branch__89aae0_idx'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['product', 'field'], name='products_ch_product_b86ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['timestamp', 'user'], name='products_ch_timesta_72aa23_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['syscom_id'], name='products_pr_syscom__86042e_idx'),
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table=None,
        ),
        migrations.AddField(
            model_name='feature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='resource',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='products.product', verbose_name='Producto'),
        ),
    ]
